### ISSUE TITLE
Handle loading errors

### ISSUE THREAD

**Issue by albertogasparin** [atlassian-labs/react-loosely-lazy#15]
First of all I would distinguish between two class of errors: network errors vs all the others. Strategies like retry make sense only for network errors and I believe if `loosely-lazy` wants to introduce some simplified error handling, it should target only this class of errors. If there is a parsing error (or any other one) we should just throw and let consumer code handle it.

So, when a chunk fails to load we currently do nothing. I see a couple of options:

#### 1. throw a dedicated error and catch it on a custom error boundary

This way such error boundary is responsible of handling only that error without affecting other types of errors.

```js
import { lazy, LazySuspense, LazyErrorBoundary } from 'react-loosely-lazy';

const AsyncComponent = lazy(() => import('./component'));

const MyApp = () => (
  <LazyErrorBoundary fallback={/* ... */}>
    <LazySuspense fallback={<Loading />}>
       <AsyncComponent />
    </LazySuspense>
  </LazyErrorBoundary>
)
```  

A downside of this approach is that it requires another wrapper. Plus the behaviour/shape of prop `fallback` is tricky: the `Suspense`-like shape does not allow passing down custom arguments, so how do we provide capabilities like manual retry or access to the error object itself? Context + dedicated hook? If fallback is instead a function `(error, actions) => <Error />` then we should pick another name to avoid confusion.

#### 2. extend LazySuspense API to render error fallback

Currently LazySuspense is 1:1 with Suspense API, however we could extend it to reduce boilerplate inside consumers: 

```js
const MyApp = () => (
    <LazySuspense fallback={<Loading />} renderError={(e) => <Error />}>
       <AsyncComponent />
    </LazySuspense>
)
```

However this might complicate transition to plain Suspense when SSR support lands, so maybe not worth it

**Comment by albertogasparin** [comment]
@MonicaOlejniczak We have an implementation that covers the basic scenarios, correct? So should we close this?

**Comment by MonicaOlejniczak** [comment]
@albertogasparin We throw errors, and can identify them using `isLoaderError`. This can be closed.
