### ISSUE TITLE
Supporting named exports

### ISSUE THREAD

**Issue by drew-walker** [atlassian-labs/react-loosely-lazy#41]
Currently at Trello we have a linting rule to enforce named exports. We don't intent to change this to default exports, so it would be a nice enhancement to support named exports so we could consider the solution an option.

**Comment by albertogasparin** [comment]
We current support named export by chaining the dynamic import promise:

```js
const MyComponent = lazyForPaint(() =>
   import('./my-component').then(({ Component }) => Component)
 );
```

However there are some limitations when it comes to making it work with SSR (with `ssr: true`) , as in that situation we need the import to be sync, so we convert `import()` to `require()` and run all chained functions as sync ones.
For instance the above get's converted by babel (on the server) to:

```js
const MyComponent = lazyForPaint(() => {
   var _temp = require('./my-component'),
       _temp2 = ({ Component }) => Component;
      return _temp2(_temp));
   }
);
```

Probably non an issue for you guys, but worth documenting

**Comment by albertogasparin** [comment]
Current support seems good enough. If edge cases arise, let's open new issues
