### ISSUE TITLE
Create different whole sets of tests for client and server options provided to the babel plugin

### ISSUE THREAD

**Issue by rohan-deshpande** [atlassian-labs/react-loosely-lazy#9]
Right now, we are covering basic functionality but not every scenario for every method. We can do this by splitting fixtures into client and server and having separate test suites for each. 

> Can we have two sets of test suites / plugin runners that run the plugin in client and server mode? Otherwise we do not validate all cases correctly, and the test output is quite confusing with implicit client values. Also, I think we should add all combinations of `lazy`, `lazyForPaint`, and `lazyAfterPaint` which can be in each fixture.

> _Originally posted by @MonicaOlejniczak in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3Mzg5NTg1MjY2/pull_request_reviews/more_threads_

**Comment by MonicaOlejniczak** [comment]
Closing because this was improved by duplicating the test scenarios between the client and server during https://github.com/atlassian-labs/react-loosely-lazy/pull/31
